server:
    port: 8082
#    context-path: /activiti-explorer
spring:
    application:
        name: activiti-explorer
    # 数据源
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password:
    activiti:
        database-schema-update: true #表示启动时检查数据库表，不存在则创建
        history-level: full #表示哪种情况下使用历史表，这里配置为full表示全部记录历史，方便绘制流程图
        db-history-used: true #true表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表
        check-process-definitions: false #校验流程定义规范
security:
    basic:
        enabled: false